NETFLIX-BUILD: Exclude aws-java-sdk from dse-pig transitive dependency.
Our version of spark has a dependency on dse-pig which depends on aws-java-sdk version 1.7.10 and declares that as a runtime dependency.
As its a runtime dependency the aws-java-sdk classes are added as part of assembly jar which resules in version conflicts during write path which is relying on aws-java-sdk version 1.7.13 or above.
We also add aws-java-sdk jars installed on the master host in spark's classpath. Now depending on which class , one from assembly jar or one from master host, get picked up by classloader we sometimes get following exception. To avoid this exception we are excluding the aws-java-sdk dependency from dse-pig.

java.lang.NoSuchMethodError: com.amazonaws.services.s3.model.ObjectMetadata.getSSEAlgorithm()Ljava/lang/String;
	at com.amazon.ws.emr.hadoop.fs.s3n.MultipartUploadOutputStream.closeAndSchedulePart(MultipartUploadOutputStream.java:531)
	at com.amazon.ws.emr.hadoop.fs.s3n.MultipartUploadOutputStream.write(MultipartUploadOutputStream.java:220)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:58)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at com.netflix.dse.utils.Utils.copy(Utils.java:610)
	at com.netflix.dse.storage.output.StorageHelper.moveTaskOutputToFinal(StorageHelper.java:429)
	at com.netflix.dse.storage.output.DeltaOutputCommitter.commitTask(DeltaOutputCommitter.java:197)
	at org.apache.spark.mapred.SparkHadoopMapRedUtil$.performCommit$1(SparkHadoopMapRedUtil.scala:101)
	at org.apache.spark.mapred.SparkHadoopMapRedUtil$.commitTask(SparkHadoopMapRedUtil.scala:139)
	at org.apache.spark.sql.hive.SparkHiveWriterContainer.commit(hiveWriterContainers.scala:267)
	at org.apache.spark.sql.hive.SparkHiveWriterContainer.close(hiveWriterContainers.scala:229)
	at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.org$apache$spark$sql$hive$execution$InsertIntoHiveTable$$writeToFile$1(InsertIntoHiveTable.scala:158)
	at org.apache.spark.sql.hive.execution.InsertIntoHiveTable$$anonfun$saveAsHiveFile$3.apply(InsertIntoHiveTable.scala:119)
	at org.apache.spark.sql.hive.execution.InsertIntoHiveTable$$anonfun$saveAsHiveFile$3.apply(InsertIntoHiveTable.scala:119)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)